import type { Metadata } from "next";
import "./globals.css";
import ReactQueryClientProvider from "@/providers/queryclient-provider";

export const metadata: Metadata = {
  title: "또글또글",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="mx-auto h-full w-full max-w-96 overflow-x-hidden border-2 bg-gray-950 px-6">
          {children}
        </div>
      </body>
    </html>
  );
}
