import { fetchBlogAnalytics } from "@/app/api/lib/blog-recap/actions";
import type { Metadata } from "next";

export async function generateMetadata({
  params,
}: {
  params: { hash: string };
}): Promise<Metadata> {
  const data = await fetchBlogAnalytics(params.hash);
  return {
    title: "blog-recap",
    description: "generated by create next app",
    openGraph: {
      images: data.result.persona.imageUrl,
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
